version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: library_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
